[package]
name = "rust-crudapi"
version = "0.1.0"
edition = "2021"

[dependencies]
cargo-watch = "8.5.2"
actix-web = "^4"
uuid = {version= "^1.9.0", features =["v4"]}
serde = {version="^1",features = ["derive"]}
env_logger = "0.11.3"
log ="^0.4"
